---
- name: Working with Linux Devices
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: "execute shell"
    shell:
        "hostname"

    register: cmd

  - debug: msg="{{cmd.stdout}}"

